version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    # volumes:
      # - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=main.py
      - FLASK_ENV=development
    expose:
      - 5000
    container_name: flask
    #command: gunicorn --bind 0.0.0.0:8000 app:app
    #command: /usr/bin/python3 main.py
    #networks: 
      #- app_network
    depends_on:
      - nginx
    ports:
      - 5000:5000 
  nginx:
    container_name: nginx 
    image: nginx
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "8039:80"
